language: php

php:
- 5.6
- 7.0
- 7.1
- 7.2

env:
  - TEST_SUITE=marketplaceeqp

sudo: false

cache:
  directories:
    - $HOME/.composer/cache

script:
  - composer validate
  - find . -name '*.php' | xargs -n 1 -P4 php -l
  - sh travis.sh