language: php

env:
  - UNIT_TEST=true

matrix:
  include:
    - php: 5.6
      # No unit tests for PHP 5.6 as PHPUnit doesn't support this version.
      env: UNIT_TEST=false
    - php: 7.0
    - php: 7.1
    - php: 7.2
    - php: 7.2
      env: UNIT_TEST=false MEQP_CHECK=true
    - php: 7.2
      env: UNIT_TEST=false MEQP_CHECK=true MEQP_LEVEL=8
    - php: 7.3
    - php: 7.2
      env: UNIT_TEST=false TOOLS_CHECK=true
      stage: deploy

  allow_failures:
    - php: 7.3
    - php: 7.2
      env: UNIT_TEST=false MEQP_CHECK=true MEQP_LEVEL=8

cache:
  directories:
    - "$HOME/.composer"
    - "$HOME/.cache/composer"
    - "$HOME/.composer/cache"

script:
  - composer validate
  - find . -name '*.php' | xargs -n 1 -P4 php -l
  - sh travis.sh

deploy:
  provider: releases
  api_key: $GITHUB_API_KEY
  skip_cleanup: true
  file: Mollie_Payment-${TRAVIS_TAG:1}.zip
  on:
    condition: TOOLS_CHECK=true
    tags: true