language: php

matrix:
  include:
    - php: 5.6
    - php: 7.0
    - php: 7.1
    - php: 7.2
      env: MEQP_CHECK=marketplaceeqp TOOLS_CHECK=true
    - php: 7.3

sudo: false

cache:
  directories:
    - $HOME/.composer
    - $HOME/.cache/composer
    - $HOME/.composer/cache

script:
  - composer validate
  - find . -name '*.php' | xargs -n 1 -P4 php -l
  - sh travis.sh
