name: Run Codesniffer with the Magento EcgM2 standard
on: push

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1

      - name: List files
        run: docker run --volume $(pwd)/:/app/data michielgerritsen/magento-ecg-coding-standard:latest bash -c "ls -al /app/data/"

      - name: Run codesniffer
        run: docker run --volume $(pwd)/:/app/data michielgerritsen/magento-ecg-coding-standard:latest bash -c "vendor/bin/phpcs --standard=EcgM2 /app/data/ --ignore=*/Test/* --severity=6 -p"
