name: Run the integration tests

on: push

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1

      - name: Start mysql docker container
        run:
          docker run -d mysql:5.7
          --build-arg MYSQL_ROOT_PASSWORD=root_password
          --build-arg MYSQL_DATABASE=magento-test
          --build-arg MYSQL_USER=magento
          --build-arg MYSQL_PASSWORD=magento

      - name: Start Magento docker container
        run:
          docker run -d
          michielgerritsen/magento-project-community-edition:php71-fpm-magento2.2.9
          --name magento-project-community-edition

      - name: Upload our code into the docker container
        run: docker cp . magento-project-community-edition:/data/extensions/ && docker exec magento-project-community-edition composer require mollie/magento2:@dev

      - name: Run tests
        run: docker exec magento-project-community-edition bash -c "cd dev/tests/quick-integration/; ../../../vendor/bin/phpunit"
