name: Run the unit tests

on: push

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1

      - name: Start Docker
        run: docker-compose -f .github/workflows/templates/docker-compose.yml up -d

      - name: Upload our code into the docker container
        run: docker cp . magento-project-community-edition:/data/extensions/ && docker exec magento-project-community-edition composer require mollie/magento2:@dev

      - name: List files
        run: ls -al extensions && ls -al extensions/workdir

      - name: Run tests
        run: docker exec magento-project-community-edition bash -c "vendor/bin/phpunit extensions/workdir/Test/Unit"
